import type { LessonDetails } from '@/lib/types';
import { lessonSupplements } from './lesson-supplements';

type Seed = {
  objectives: string[];
  mentalModel: string;
  how: { intro: string; bullets: string[] };
  decide: { intro: string; bullets: string[] };
  scenario: { title: string; situation: string; walkthrough: string[]; takeaway: string };
  check: { question: string; options: string[]; answer: number; explanation: string };
  resources: { title: string; href: string; note: string }[];
};

const detail = (seed: Seed): LessonDetails => ({
  objectives: seed.objectives,
  mentalModel: seed.mentalModel,
  sections: [
    { title: 'How it works', paragraphs: [seed.how.intro], bullets: seed.how.bullets },
    { title: 'How to make the production decision', paragraphs: [seed.decide.intro], bullets: seed.decide.bullets },
  ],
  scenario: seed.scenario,
  checks: [seed.check],
  resources: seed.resources,
});

const effectiveAgents = { title: 'Building effective agents', href: 'https://www.anthropic.com/engineering/building-effective-agents', note: 'Anthropic’s guide to workflow and agent patterns.' };
const toolConcepts = { title: 'How tool use works', href: 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/how-tool-use-works', note: 'Tool contracts and the client/server execution boundary.' };
const claudeCodeOverview = { title: 'How Claude Code works', href: 'https://code.claude.com/docs/en/how-claude-code-works', note: 'Current Claude Code execution and context model.' };
const codeBestPractices = { title: 'Claude Code best practices', href: 'https://code.claude.com/docs/en/best-practices', note: 'Official patterns for effective repository work.' };
const promptOverview = { title: 'Prompt engineering overview', href: 'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview', note: 'A workflow for defining success and improving prompts.' };
const structuredOutputs = { title: 'Structured outputs', href: 'https://platform.claude.com/docs/en/build-with-claude/structured-outputs', note: 'Schema-constrained JSON and strict tool use.' };
const contextWindows = { title: 'Context windows', href: 'https://platform.claude.com/docs/en/build-with-claude/context-windows', note: 'How context is counted and what happens near the limit.' };

export const lessonDetails: Record<string, LessonDetails> = {
  'd1-2': detail({
    objectives: ['Distinguish a workflow from an agent using observable requirements.', 'Select chaining, routing, parallelization, or adaptive planning.', 'Explain the cost and reliability trade-off of added autonomy.'],
    mentalModel: 'A workflow follows a path your code already knows; an agent discovers the path while working. Autonomy is a response to uncertainty, not a maturity badge.',
    how: { intro: 'Start by asking where the next-step decision lives. In a workflow, application logic chooses the next stage. In an agent, the model examines intermediate evidence and decides which tool or subtask comes next.', bullets: ['Prompt chaining fits ordered transformations with stable stage contracts.', 'Routing chooses one specialized path from a known menu.', 'Parallelization runs independent work concurrently and aggregates it.', 'Evaluator–optimizer loops use an explicit rubric and a bounded revision policy.', 'Agents fit open-ended work where findings materially change the plan.'] },
    decide: { intro: 'Use the least adaptive pattern that satisfies the requirement. Every autonomous decision adds variance, latency, cost, and a new failure branch that must be observed and tested.', bullets: ['Choose a workflow when the path, gates, and completion conditions are known.', 'Choose an agent when decomposition or tool selection depends on evidence not available upfront.', 'Keep irreversible actions behind deterministic approval even inside an agent.', 'Measure whether adaptation improves outcomes enough to justify its operational cost.'] },
    scenario: { title: 'Worked example: insurance intake versus investigation', situation: 'One system extracts a claim, validates required fields, and routes by claim type. Another investigates a suspicious claim across changing evidence sources.', walkthrough: ['Model extraction, validation, and routing as a deterministic workflow.', 'Use a fixed escalation gate for missing identity or high claim value.', 'Give the investigation agent read-only evidence tools and an explicit coverage goal.', 'Require the agent to return findings and provenance, not execute settlement.'], takeaway: 'Known processing paths are workflows; evidence-dependent exploration may be agentic, while consequential gates remain deterministic.' },
    check: { question: 'Which requirement most strongly justifies an agent instead of a fixed chain?', options: ['The steps must always run in the same order', 'The next source to inspect depends on what earlier sources reveal', 'The output must match a JSON schema', 'Latency must be tightly predictable'], answer: 1, explanation: 'An agent is justified when intermediate evidence changes the plan. Fixed order, schema guarantees, and strict latency generally favor workflows.' },
    resources: [effectiveAgents],
  }),
  'd1-3': detail({
    objectives: ['Define coordinator and specialist responsibilities.', 'Design explicit context and output contracts for subagents.', 'Aggregate partial or conflicting results without losing provenance.'],
    mentalModel: 'The coordinator is the accountable hub; specialists are isolated functions with judgment. Nothing crosses an agent boundary unless the coordinator passes or receives it explicitly.',
    how: { intro: 'A coordinator decomposes the goal, chooses specialists, sends bounded assignments, and reconciles their results. Each specialist starts with an isolated context, which reduces distraction but makes explicit handoff design essential.', bullets: ['Pass the goal, relevant facts, constraints, allowed tools, and output schema.', 'Give specialists distinct, non-overlapping responsibilities.', 'Return conclusions with evidence, coverage, uncertainty, and errors.', 'Keep cross-cutting policy and final accountability with the coordinator.'] },
    decide: { intro: 'Use subagents when isolation, parallel expertise, or independent review creates a measurable benefit. A deterministic function is better for mechanical transformations.', bullets: ['Parallelize specialists only when their inputs are independent.', 'Do not give a synthesis specialist write tools it does not need.', 'Preserve partial success when one specialist fails.', 'Resolve conflict using evidence quality and stated policy, not majority vote.'] },
    scenario: { title: 'Worked example: vendor security review', situation: 'A coordinator must assess legal terms, security controls, and data architecture for one vendor.', walkthrough: ['Send each specialist the same vendor identity and shared evaluation rubric.', 'Give legal only contract documents, security only control evidence, and architecture only data-flow materials.', 'Require findings with severity, source location, and uncertainty.', 'Let the coordinator reconcile overlaps and identify missing evidence.'], takeaway: 'Isolation improves focus only when handoffs carry the exact shared facts and output contract needed for synthesis.' },
    check: { question: 'What should a coordinator assume about a newly invoked subagent?', options: ['It has the parent conversation automatically', 'It has every tool the parent has', 'It knows only the context explicitly supplied to it', 'It can communicate directly with every other specialist'], answer: 2, explanation: 'Subagents are isolated. Required history, constraints, and facts must be passed explicitly.' },
    resources: [effectiveAgents, claudeCodeOverview],
  }),
  'd1-4': detail({
    objectives: ['Identify true data and authorization dependencies.', 'Build execution waves for safe concurrency.', 'Return parallel results in a form that preserves correlation.'],
    mentalModel: 'Parallelism is a property of the dependency graph, not of how many tasks are visible. Two calls are concurrent only when neither consumes or authorizes the other.',
    how: { intro: 'Model work as nodes and edges. Nodes with no unresolved incoming edge can run in the same wave. Join only when every required result is available, then unlock dependent work.', bullets: ['Searches of independent sources often belong in one wave.', 'A lookup and an action based on that lookup are sequential.', 'Identity verification is an authorization dependency, not an optimization detail.', 'For multiple client tool calls, return all results together and preserve each tool-use ID.'] },
    decide: { intro: 'Concurrency improves latency but can amplify rate limits, load, and side effects. Set explicit concurrency limits and keep failure behavior local to each branch.', bullets: ['Classify dependencies as data, authorization, resource, or ordering constraints.', 'Use bounded concurrency for large fan-outs.', 'Define whether one branch failure blocks aggregation or creates a coverage gap.', 'Never speculate past a missing prerequisite to save time.'] },
    scenario: { title: 'Worked example: customer with two issues', situation: 'A customer asks about a delayed order and an unrelated loyalty-points balance.', walkthrough: ['Verify the customer once.', 'After verification, run order lookup and points lookup concurrently.', 'If the order lookup fails, preserve the points result.', 'Aggregate both outcomes and label the order coverage gap.'], takeaway: 'Parallelize independent evidence gathering after shared prerequisites; preserve branch-level errors instead of failing the entire request.' },
    check: { question: 'Which pair is unsafe to execute in parallel?', options: ['Search two independent document stores', 'Inspect two unrelated files', 'Verify identity and issue the requested refund', 'Classify two independent support tickets'], answer: 2, explanation: 'The refund depends on successful identity verification, so the authorization edge requires serialization.' },
    resources: [effectiveAgents, toolConcepts],
  }),
  'd1-5': detail({
    objectives: ['Separate behavioral guidance from enforceable controls.', 'Place checks before or after actions correctly.', 'Design layered controls for consequential tools.'],
    mentalModel: 'Prompts influence model choices; code controls what the system can actually do. A hard requirement is real only when violating it is technically prevented or detected at the correct boundary.',
    how: { intro: 'Use prompts for judgment, tone, prioritization, and explanation. Use schemas to constrain shape. Use permissions, pre-action hooks, and application logic to block unauthorized actions. Use post-action processing for normalization, redaction, auditing, and feedback.', bullets: ['Pre-action controls prevent execution.', 'Post-action controls inspect or transform completed output.', 'Schemas validate structure, not business authorization.', 'Human approval belongs before an irreversible high-impact action.'] },
    decide: { intro: 'For every rule, ask what happens if the model ignores it. If the consequence is unacceptable, enforce the rule outside the prompt and log the decision.', bullets: ['Check current identity and authority immediately before execution.', 'Use allowlists and thresholds close to the tool boundary.', 'Make consequential operations idempotent.', 'Treat model-based hooks as probabilistic unless backed by deterministic code.'] },
    scenario: { title: 'Worked example: refund threshold', situation: 'Support policy allows agents to refund up to $100 after verified identity.', walkthrough: ['The prompt tells Claude when refunds are appropriate.', 'A pre-action gate checks verified identity and amount.', 'Amounts above $100 are rejected with a structured escalation result.', 'A post-action hook records the approved refund and redacts unnecessary account data.'], takeaway: 'Use the prompt for policy reasoning, but enforce identity and monetary authority in code before the refund tool runs.' },
    check: { question: 'Where should an absolute $100 refund limit be enforced?', options: ['Only in the system prompt', 'In application logic before tool execution', 'In a post-action summary', 'In a few-shot example'], answer: 1, explanation: 'A hard business limit requires deterministic enforcement before the action; prompts and examples cannot guarantee compliance.' },
    resources: [toolConcepts, { title: 'Claude Code hooks guide', href: 'https://code.claude.com/docs/en/hooks-guide', note: 'Lifecycle interception and deterministic automation.' }],
  }),
  'd1-6': detail({
    objectives: ['Choose what state must survive an interruption.', 'Decide between resume, restart, and fork.', 'Detect when stored observations have become stale.'],
    mentalModel: 'A transcript is history; a recovery manifest is operational state. Resume only when the world described by that state is still valid.',
    how: { intro: 'Persist a compact manifest containing the objective, completed steps, exact critical values, artifacts, evidence sources, tool errors, pending work, and assumptions. Record freshness or version markers for external state.', bullets: ['Resume when inputs and observations are still valid.', 'Restart from a verified summary when the environment changed.', 'Fork when comparing divergent approaches from one trusted baseline.', 'Never treat a stale tool observation as current merely because it remains in context.'] },
    decide: { intro: 'Recovery choice depends on validity, not convenience. Revalidate cheap and consequential facts first, then reuse only the work that remains trustworthy.', bullets: ['Record repository commit, record version, or retrieval timestamp.', 'Separate durable decisions from ephemeral observations.', 'Make completed side effects idempotently discoverable.', 'Carry forward unresolved errors and ownership.'] },
    scenario: { title: 'Worked example: interrupted migration', situation: 'An agent planned a repository migration yesterday and completed three of eight files before stopping.', walkthrough: ['Read the saved manifest and exact base commit.', 'Compare the current repository state with that commit.', 'Keep completed edits that still apply.', 'Re-run discovery for changed dependencies before resuming pending files.'], takeaway: 'Resume artifacts, not assumptions; revalidate observations whenever the underlying system may have changed.' },
    check: { question: 'When is a fresh start safer than resuming the full old context?', options: ['When the previous session was short', 'When earlier tool observations may no longer describe current state', 'Whenever a task has more than three steps', 'Only after a model error'], answer: 1, explanation: 'Stale external observations can make resumed reasoning unsafe. Start from a verified summary and reacquire current evidence.' },
    resources: [contextWindows, codeBestPractices],
  }),
  'd1-7': detail({
    objectives: ['Bound autonomous work with outcome and resource constraints.', 'Design checkpoints and escalation triggers.', 'Create a useful human handoff from partial work.'],
    mentalModel: 'Autonomy is a delegated budget with a definition of done. A loop count is only a safety cap; it does not say whether the objective was achieved.',
    how: { intro: 'Give the agent an outcome, permissions, time or cost budget, completion tests, checkpoint policy, and escalation conditions. Observe actions and preserve state continuously so interruption does not erase useful work.', bullets: ['Completion criteria describe the achieved state.', 'Safety caps limit damage but do not imply success.', 'Checkpoints surface risk before costly or irreversible branches.', 'Handoffs include verified facts, evidence, attempts, errors, and recommended next action.'] },
    decide: { intro: 'Increase oversight as reversibility decreases and uncertainty rises. Let an agent explore broadly with read-only tools, but narrow authority near writes, spending, communication, or policy exceptions.', bullets: ['Use tool allowlists and per-action approval tiers.', 'Escalate inability to progress, not ordinary recoverable failures.', 'Preserve partial results and coverage gaps.', 'Give the human enough state to continue without repeating the investigation.'] },
    scenario: { title: 'Worked example: billing dispute handoff', situation: 'The agent verifies the account and finds conflicting invoices but cannot determine which contract amendment applies.', walkthrough: ['Record verified identity and invoice IDs.', 'Attach the conflicting amendment evidence and dates.', 'List attempted policy lookups and the missing authority.', 'Recommend contract-specialist review without issuing a credit.'], takeaway: 'A good handoff transfers verified state and the unresolved decision—not merely the last user message.' },
    check: { question: 'Why is “stop after 10 iterations” insufficient as the main completion rule?', options: ['Ten is always too many', 'It limits runtime but does not prove the outcome was achieved', 'Agents cannot count iterations', 'It prevents tool use'], answer: 1, explanation: 'Iteration limits are useful safety caps, but success requires explicit outcome criteria and validation.' },
    resources: [effectiveAgents],
  }),

  'd2-1': detail({
    objectives: ['Write a tool contract that supports reliable selection.', 'Separate overlapping tool responsibilities.', 'Specify inputs, outputs, constraints, and side effects.'],
    mentalModel: 'A tool schema validates arguments; the description teaches when the capability belongs in the plan. Reliable tool use needs both.',
    how: { intro: 'Design tools around one clear operation. The name should express the action and object, while the description states when to use it, when not to use it, required prerequisites, and the meaning of its result.', bullets: ['Define identifiers, formats, units, defaults, and bounds.', 'Distinguish read-only queries from consequential writes.', 'Return stable machine-readable success and error shapes.', 'Avoid several tools that appear interchangeable from the model’s perspective.'] },
    decide: { intro: 'Start from the decisions the model must make. Split tools when permissions, side effects, latency, or error recovery differ; combine only when the operations are inseparable.', bullets: ['Prefer get_order and request_refund over manage_order.', 'Expose only fields needed for the task.', 'Use enums and descriptions for meaningful closed choices.', 'Test ambiguous prompts and inspect misrouted calls before adding more prompt text.'] },
    scenario: { title: 'Worked example: order service', situation: 'An early design exposes process_order, manage_order, and order_action with nearly identical descriptions.', walkthrough: ['List the distinct user intents.', 'Create search_orders, get_order_details, and request_refund.', 'Document prerequisites and side effects for each.', 'Test boundary prompts such as “Can this be refunded?” versus “Refund it.”'], takeaway: 'Tool boundaries should mirror distinct intent, authority, and side-effect boundaries.' },
    check: { question: 'Which change most improves reliable tool selection?', options: ['Add more optional fields', 'Rename every tool with a shorter name', 'Give each tool a distinct purpose and state when to use and not use it', 'Put all operations into one flexible tool'], answer: 2, explanation: 'Distinct responsibilities plus use/non-use guidance reduce ambiguity more than schema size or generic flexibility.' },
    resources: [{ title: 'Define tools', href: 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/implement-tool-use', note: 'Current tool definition, schema, and description guidance.' }, toolConcepts],
  }),
  'd2-2': detail({
    objectives: ['Classify tool outcomes for the correct recovery path.', 'Design machine-actionable error payloads.', 'Prevent blind retries and false failures.'],
    mentalModel: 'An error contract is a routing contract. It should tell the agent and application whether to retry, repair input, choose an alternative, explain, or escalate.',
    how: { intro: 'Represent success, empty success, validation failure, permission failure, business-rule denial, transient failure, and uncertain outcome distinctly. Include a stable code, retryability, safe message, and attempted operation.', bullets: ['Transient failures may retry with limits and backoff.', 'Validation failures require corrected input.', 'Permission and business-rule failures should not be blindly retried.', 'Zero matches is usually a successful query with an empty result.', 'Uncertain write outcomes require idempotency checks before retry.'] },
    decide: { intro: 'Classify errors at the boundary where the evidence is strongest. Do not expose secrets or raw infrastructure traces to the model or end user.', bullets: ['Separate internal diagnostic detail from a safe model-facing message.', 'Preserve correlation IDs for operators.', 'Return is_error for failed client tool execution.', 'Measure retry yield and repeated failure patterns.'] },
    scenario: { title: 'Worked example: order lookup timeout', situation: 'The order service times out after ten seconds.', walkthrough: ['Return code UPSTREAM_TIMEOUT and retryable true.', 'Preserve the order ID and attempt correlation.', 'Retry within a small budget using backoff.', 'After the budget, explain temporary unavailability or use an approved alternative.'], takeaway: 'The error should enable the next safe action, not merely announce failure.' },
    check: { question: 'A search completes successfully and finds no matching records. How should it be represented?', options: ['As a transient infrastructure error', 'As empty success', 'As a permission denial', 'As a schema failure'], answer: 1, explanation: 'The operation succeeded. An empty result has different recovery behavior from a failed query.' },
    resources: [{ title: 'Handle tool calls', href: 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/handle-tool-calls', note: 'Returning tool results and marking execution errors.' }],
  }),
  'd2-3': detail({
    objectives: ['Choose auto, any, forced, or disabled tool selection.', 'Separate selection controls from authorization.', 'Apply least privilege to each role.'],
    mentalModel: 'tool_choice controls the model’s first selection behavior; permissions control what execution is actually allowed. Neither substitutes for the other.',
    how: { intro: 'Auto allows a direct answer or a tool call. Any requires one of the supplied tools. Forced selection names the required tool. None disables tool calls where supported. The available tool set still defines the model’s visible capabilities.', bullets: ['Use auto when a tool is optional.', 'Use any when structured action is mandatory but several tools are valid.', 'Force a named tool for a mandatory first-stage contract.', 'Expose only the tools required for the current role and phase.'] },
    decide: { intro: 'Use deterministic selection controls when the workflow contract requires a tool call. Do not rely on prompt wording for guarantees, and do not confuse forced selection with permission to execute the resulting action.', bullets: ['Validate authorization after selection.', 'Narrow the active tool set by phase.', 'Separate read and write capabilities.', 'Account for model-feature compatibility when using advanced reasoning modes.'] },
    scenario: { title: 'Worked example: document intake', situation: 'Every uploaded invoice must first be converted to a validated extraction object.', walkthrough: ['Force the extraction tool for the first stage.', 'Validate the structured result.', 'Then expose optional lookup or review tools.', 'Keep payment tools unavailable to the intake role.'], takeaway: 'Force a mandatory interface stage, then still validate and authorize everything that follows.' },
    check: { question: 'Which setting fits a stage that must produce one of several approved structured actions?', options: ['auto', 'any', 'none', 'A longer prompt only'], answer: 1, explanation: 'Any requires a tool call while allowing the model to choose among the supplied tools.' },
    resources: [{ title: 'Tool use overview', href: 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/overview', note: 'Tool-choice modes and strict schema behavior.' }],
  }),
  'd2-4': detail({
    objectives: ['Explain the MCP host, client, and server relationship.', 'Choose between tools, resources, and prompts.', 'Place permissions with the host rather than the server description.'],
    mentalModel: 'MCP standardizes how capabilities are described and exchanged; the host still decides what enters context and what the user or model may invoke.',
    how: { intro: 'An MCP host embeds one or more clients that connect to servers. Servers can expose model-controlled tools, application-controlled resources, and user-invoked prompt templates. The protocol separates discovery from host policy.', bullets: ['Tools perform operations or fresh queries.', 'Resources expose addressable read-only content.', 'Prompts package reusable user-invoked workflows.', 'The host controls approval, context inclusion, and user experience.'] },
    decide: { intro: 'Choose the primitive based on who should initiate it and whether it acts or describes. Prefer a maintained server for standard integrations when its trust and contracts fit; build custom for organization-specific behavior.', bullets: ['Use a resource for catalogs and reference data.', 'Use a tool for an action or live query.', 'Use a prompt for a reusable workflow a user selects.', 'Review server trust, data access, and side effects before enabling it.'] },
    scenario: { title: 'Worked example: document workspace server', situation: 'A team needs to browse documents, search them, and run a standard review workflow.', walkthrough: ['Expose the document catalog as resources.', 'Expose search and update as distinct tools.', 'Expose “review this document” as a user-selectable prompt.', 'Let the host gate the update tool by permission.'], takeaway: 'Model tools act, application resources inform, and user prompts initiate reusable workflows.' },
    check: { question: 'Which MCP primitive best represents a read-only catalog addressed by URI?', options: ['Tool', 'Resource', 'Prompt', 'Hook'], answer: 1, explanation: 'Resources are application-controlled, addressable content; tools are model-controlled operations.' },
    resources: [{ title: 'MCP specification', href: 'https://modelcontextprotocol.io/specification/latest', note: 'Authoritative protocol concepts and lifecycle.' }],
  }),
  'd2-5': detail({
    objectives: ['Place shared MCP configuration and secrets correctly.', 'Evaluate integrations using least privilege.', 'Use targeted file discovery before broad reading.'],
    mentalModel: 'Configuration can be shared; credentials and personal trust decisions cannot. Discovery should narrow context before expensive reading or execution.',
    how: { intro: 'Commit safe project-scoped server configuration so the team shares endpoints and commands. Inject credentials from the environment or an approved store. Review every server’s provenance, permissions, and data path.', bullets: ['Never commit tokens in MCP configuration.', 'Separate project, local, and user scope.', 'Grant each server and agent only required capabilities.', 'Use Glob for path discovery, Grep for content discovery, then Read targeted files.'] },
    decide: { intro: 'Choose scope based on ownership and sensitivity. Start repository exploration with a question and a search pattern, not a full-tree read.', bullets: ['Team behavior belongs in version control.', 'Personal experiments belong in local or user scope.', 'Secrets stay outside committed configuration.', 'Escalate broad shell access and write tools carefully.'] },
    scenario: { title: 'Worked example: shared issue-tracker integration', situation: 'A team wants one MCP configuration while each developer has separate credentials.', walkthrough: ['Commit the server command and environment-variable names.', 'Keep actual tokens in each developer’s environment.', 'Expose read-only issue tools to review agents.', 'Grant update capability only to the workflow that needs it.'], takeaway: 'Share safe configuration and capability intent, while keeping secrets and excess authority out of the repository.' },
    check: { question: 'Where should a team-shared MCP API token be stored?', options: ['Directly in the committed project config', 'In CLAUDE.md', 'In an environment variable or approved secret store', 'Inside the tool description'], answer: 2, explanation: 'Commit safe configuration, never credentials. Inject secrets at runtime.' },
    resources: [{ title: 'Claude Code MCP', href: 'https://code.claude.com/docs/en/mcp', note: 'Current MCP configuration and scope behavior in Claude Code.' }, codeBestPractices],
  }),

  'd3-1': detail({
    objectives: ['Map settings to managed, project, local, or user scope.', 'Prevent personal preferences and secrets from entering shared config.', 'Explain precedence as an organizational policy decision.'],
    mentalModel: 'Scope answers who owns the behavior and who should receive it. Put a rule at the narrowest scope that reaches every intended user.',
    how: { intro: 'Managed scope represents organization policy, project scope is shared with the repository, local scope customizes one checkout for one developer, and user scope follows one person across projects.', bullets: ['Shared build and architecture rules belong to project scope.', 'Machine-specific paths and project-local preferences belong to local scope.', 'Personal defaults belong to user scope.', 'Non-overridable organization policy belongs to managed scope.'] },
    decide: { intro: 'Classify every setting by owner, audience, portability, and sensitivity. Avoid duplication across scopes because conflicting instructions make behavior hard to debug.', bullets: ['Do not put team standards only in user scope.', 'Do not commit secrets or workstation paths.', 'Use managed policy sparingly for real organization controls.', 'Document which scope owns important behavior.'] },
    scenario: { title: 'Worked example: test commands and personal style', situation: 'A repository has one canonical test command, while one developer prefers more explanation in responses.', walkthrough: ['Commit the test command at project scope.', 'Keep the response-style preference at user scope.', 'Store a local test database path in ignored local settings.', 'Use managed scope only if the organization must enforce a restriction.'], takeaway: 'Scope follows ownership: team facts travel with the repository; personal preferences travel with the person.' },
    check: { question: 'Where should a version-controlled team test command live?', options: ['User scope', 'Project scope', 'Local scope only', 'A personal shell history'], answer: 1, explanation: 'A shared repository convention belongs in project scope so every contributor receives it.' },
    resources: [{ title: 'Claude Code settings', href: 'https://code.claude.com/docs/en/settings', note: 'Configuration files, scopes, and precedence.' }],
  }),
  'd3-2': detail({
    objectives: ['Keep always-on repository instructions compact.', 'Move conditional conventions into path rules.', 'Reduce irrelevant context and contradictory guidance.'],
    mentalModel: 'CLAUDE.md is the project’s operating card, not its encyclopedia. Conditional knowledge should appear only when the matching work makes it relevant.',
    how: { intro: 'Use CLAUDE.md for stable commands, architecture boundaries, repository layout, and non-obvious constraints. Use modular path rules for conventions that apply only to particular files or directories.', bullets: ['Prefer executable commands over narrative setup history.', 'State boundaries and reasons concisely.', 'Apply API rules only to API paths.', 'Apply testing conventions only when test files are in scope.'] },
    decide: { intro: 'Every always-on line consumes attention on every task. Keep material there only if forgetting it would frequently cause a real error across the repository.', bullets: ['Move long playbooks to skills.', 'Move conditional instructions to rules.', 'Delete duplicated or obsolete guidance.', 'Resolve contradictions at the highest appropriate owner.'] },
    scenario: { title: 'Worked example: monorepo instructions', situation: 'A monorepo has different conventions for the API, web client, and integration tests.', walkthrough: ['Keep universal build and architecture facts in root CLAUDE.md.', 'Add API-specific rules for server paths.', 'Add frontend rules for client paths.', 'Add test rules that load only for matching test files.'], takeaway: 'Modular instructions improve signal by loading a convention only where it can affect the work.' },
    check: { question: 'What belongs in root CLAUDE.md?', options: ['A full copy of every framework manual', 'Stable repository-wide commands and constraints', 'Every developer’s personal preferences', 'API credentials'], answer: 1, explanation: 'Root instructions should be concise, stable, and broadly relevant to work in the repository.' },
    resources: [{ title: 'Claude Code memory', href: 'https://code.claude.com/docs/en/memory', note: 'CLAUDE.md hierarchy and modular rules.' }, codeBestPractices],
  }),
  'd3-3': detail({
    objectives: ['Identify when a skill is the right extension point.', 'Write descriptions that support reliable discovery.', 'Control context and tools for verbose workflows.'],
    mentalModel: 'A skill is reusable knowledge plus procedure loaded when relevant; it is not a universal policy or an autonomous worker.',
    how: { intro: 'Package focused instructions, references, scripts, and assets around a repeatable task. The description must clearly state the trigger and capability because it is the routing surface.', bullets: ['Use a skill for repeatable, task-specific workflows.', 'Keep always-on rules in project instructions instead.', 'Use scripts for deterministic repeated mechanics.', 'Restrict tools or fork context when the workflow is noisy or sensitive.'] },
    decide: { intro: 'Create a skill when reuse and consistent procedure matter enough to justify maintenance. Keep its scope narrow so matching is predictable and its instructions stay authoritative.', bullets: ['Name the task and expected output.', 'Include acceptance criteria and references.', 'Avoid secrets and environment-specific data.', 'Test explicit invocation and natural-language matching.'] },
    scenario: { title: 'Worked example: code-review skill', situation: 'A team repeatedly reviews pull requests against the same security and correctness rubric.', walkthrough: ['Define a precise description for repository review.', 'Include the rubric and output schema.', 'Restrict the workflow to read-only tools.', 'Return evidence, severity, and remediation for each finding.'], takeaway: 'Skills make repeatable judgment workflows portable without loading the full playbook on every task.' },
    check: { question: 'Which requirement is the best fit for a skill?', options: ['An absolute prohibition on deleting production data', 'A reusable code-review workflow with a rubric', 'A secret API token', 'A one-line deterministic formatter'], answer: 1, explanation: 'A reusable knowledge-rich workflow fits a skill; hard prohibitions need deterministic controls.' },
    resources: [{ title: 'Claude Code skills', href: 'https://code.claude.com/docs/en/skills', note: 'Skill structure, discovery, and execution behavior.' }],
  }),
  'd3-4': detail({
    objectives: ['Differentiate subagents, hooks, and permissions.', 'Choose pre- versus post-tool interception.', 'Combine isolation and deterministic enforcement.'],
    mentalModel: 'Subagents isolate reasoning, permissions limit capability, and hooks intercept lifecycle events. They solve different layers of the system.',
    how: { intro: 'A subagent receives an isolated context and tool set. Permissions define which actions are allowed or require approval. Hooks execute at defined lifecycle points and can block, transform, log, or provide feedback.', bullets: ['PreToolUse can block before execution.', 'PostToolUse can lint, normalize, or report after success.', 'Tool allowlists reduce a specialist’s attack and error surface.', 'LLM-based hook judgment remains probabilistic.'] },
    decide: { intro: 'Use the most direct control. Isolate a noisy specialty with a subagent, remove unnecessary capability with permissions, and enforce hard lifecycle rules with deterministic hook code.', bullets: ['Do not create a subagent for a mechanical script.', 'Do not trust a prompt to enforce an absolute restriction.', 'Make block messages actionable.', 'Test hook failure and bypass behavior.'] },
    scenario: { title: 'Worked example: protected migrations', situation: 'An exploration agent may inspect the repository but must never edit production migration files.', walkthrough: ['Give the agent read-only exploration tools.', 'Deny edits to the protected path in permissions.', 'Add a deterministic pre-tool hook as defense in depth.', 'Use a separate approved workflow for migration changes.'], takeaway: 'Context isolation is useful, but capability removal and pre-action enforcement create the guarantee.' },
    check: { question: 'Which mechanism should prevent edits to a protected directory?', options: ['A reminder in the final response', 'A deterministic pre-tool control or permission', 'A post-tool summary', 'A larger context window'], answer: 1, explanation: 'Pre-action permissions or hooks stop the edit before it occurs.' },
    resources: [{ title: 'Subagents', href: 'https://code.claude.com/docs/en/sub-agents', note: 'Specialist configuration and context isolation.' }, { title: 'Hooks guide', href: 'https://code.claude.com/docs/en/hooks-guide', note: 'Lifecycle events and hook design.' }],
  }),
  'd3-5': detail({
    objectives: ['Match planning depth to uncertainty and blast radius.', 'Use tests and examples as execution feedback.', 'Avoid both premature editing and planning overhead.'],
    mentalModel: 'Planning buys down uncertainty before expensive change. Its value rises with coupling, ambiguity, irreversibility, and the number of viable approaches.',
    how: { intro: 'Use direct execution for a small, clear, reversible change with known validation. Use plan mode when scope or dependencies are unknown, multiple approaches matter, or a human should approve the design.', bullets: ['Explore before editing cross-cutting architecture.', 'State affected components and validation strategy.', 'Break execution into independently verifiable slices.', 'Let real test failures refine the implementation.'] },
    decide: { intro: 'Plan enough to expose consequential choices, then act. A plan should reduce risk, not become a substitute for testing or delivery.', bullets: ['Estimate blast radius and rollback difficulty.', 'Identify decisions that need approval.', 'Prefer reversible intermediate states.', 'Stop planning when the next safe action is clear.'] },
    scenario: { title: 'Worked example: typo versus service extraction', situation: 'One task fixes a mislabeled button; another extracts authentication from a monolith.', walkthrough: ['Fix and test the label directly.', 'For extraction, map callers, state, data flow, and deployment constraints.', 'Compare migration strategies.', 'Execute the approved plan in tested increments.'], takeaway: 'Planning depth should follow uncertainty and consequence, not a ritual applied equally to every task.' },
    check: { question: 'Which task most needs plan mode?', options: ['Correcting a known spelling error', 'Renaming one local variable', 'Extracting a shared service across many dependent modules', 'Re-running an existing unit test'], answer: 2, explanation: 'A cross-cutting architectural change has unknown dependencies and material trade-offs.' },
    resources: [codeBestPractices],
  }),
  'd3-6': detail({
    objectives: ['Run Claude Code non-interactively in automation.', 'Design machine-readable review output.', 'Separate generation from independent review.'],
    mentalModel: 'CI is a machine consumer. Every prompt, output, failure, and exit condition must be deterministic enough for another program to act on.',
    how: { intro: 'Use print/headless mode rather than an interactive session. Provide stable repository context, the exact diff and relevant code, a focused rubric, and a structured result contract.', bullets: ['Use -p or --print for non-interactive execution.', 'Request fields such as severity, evidence, location, and remediation.', 'Deduplicate against prior findings when necessary.', 'Fail or warn based on explicit policy outside the model.'] },
    decide: { intro: 'Automate categories with acceptable precision and observable evidence. Keep the generated result advisory until calibration supports a blocking gate.', bullets: ['Review generated code in an independent context.', 'Measure false positives by category.', 'Preserve logs and exact model/config version.', 'Do not parse free-form prose when a schema is available.'] },
    scenario: { title: 'Worked example: pull-request review', situation: 'A workflow should flag high-confidence security regressions without posting duplicates.', walkthrough: ['Pass the diff plus relevant surrounding code.', 'Supply the security rubric and previous findings.', 'Require structured findings with fingerprints.', 'Apply deterministic deduplication and severity policy.'], takeaway: 'The model proposes evidence-backed findings; CI code decides how those findings affect the build.' },
    check: { question: 'Why use an independent review context?', options: ['It guarantees no errors', 'It avoids asking the generation context to validate its own assumptions', 'It makes the output longer', 'It removes the need for tests'], answer: 1, explanation: 'Independence reduces shared blind spots, though it still does not replace deterministic tests.' },
    resources: [{ title: 'CLI reference', href: 'https://code.claude.com/docs/en/cli-reference', note: 'Headless invocation and output controls.' }, codeBestPractices],
  }),

  'd4-1': detail({
    objectives: ['Define measurable success before prompt iteration.', 'Construct representative and adversarial evaluation sets.', 'Compare revisions on stable evidence.'],
    mentalModel: 'A prompt change is an experiment. Without a fixed evaluation target, improvement is only an anecdote.',
    how: { intro: 'Specify desired behavior, unacceptable failures, latency and cost constraints, and the business trade-off between false positives and false negatives. Build cases that represent the real input distribution and its dangerous edges.', bullets: ['Include normal, hard, ambiguous, and adversarial cases.', 'Use labeled expected outcomes or a precise rubric.', 'Measure performance by meaningful segment.', 'Keep a holdout set to detect overfitting.'] },
    decide: { intro: 'Choose metrics that reflect consequences. Extraction needs field-level accuracy; classification may need precision and recall; open-ended review needs calibrated rubric scores and human agreement.', bullets: ['Version prompts and evaluation data.', 'Compare on the same cases.', 'Inspect regressions, not only averages.', 'Set release thresholds before seeing results.'] },
    scenario: { title: 'Worked example: code-review precision', situation: 'A review prompt finds many theoretical issues but engineers ignore it because most are not actionable.', walkthrough: ['Label a representative set of prior diffs.', 'Define actionable severity and required evidence.', 'Measure precision by issue category.', 'Remove or rewrite categories with persistently poor precision.'], takeaway: 'Optimize against a stable definition of useful behavior, not the persuasiveness of individual outputs.' },
    check: { question: 'What should happen before rewriting a weak production prompt?', options: ['Add as many instructions as possible', 'Define success criteria and a representative evaluation set', 'Switch output to Markdown', 'Increase temperature'], answer: 1, explanation: 'Evals make changes measurable and reveal whether the revision improves the cases that matter.' },
    resources: [promptOverview, { title: 'Define success criteria', href: 'https://platform.claude.com/docs/en/test-and-evaluate/define-success', note: 'Evaluation targets and measurable criteria.' }],
  }),
  'd4-2': detail({
    objectives: ['Translate vague quality goals into decision criteria.', 'Use examples to teach boundaries and format.', 'Balance example coverage against context cost.'],
    mentalModel: 'Instructions define the rule; examples locate the boundary. Use examples where words alone leave several plausible interpretations.',
    how: { intro: 'State what to include, what to exclude, how to prioritize, and how to handle uncertainty. Add a small set of positive, negative, and edge examples that demonstrate the desired distinction.', bullets: ['Use concrete definitions instead of “be careful.”', 'Show acceptable negatives, not only positives.', 'Keep examples diverse and relevant.', 'Match the exact target output structure.'] },
    decide: { intro: 'Add examples after identifying a recurring ambiguity. Too many redundant examples consume context and can cause imitation of surface details rather than the underlying rule.', bullets: ['Choose examples around observed failure boundaries.', 'Explain why the labels differ when useful.', 'Re-evaluate after changing examples.', 'Remove examples that no longer add distinct information.'] },
    scenario: { title: 'Worked example: ticket escalation', situation: 'A model escalates every angry message even when the issue is routine and fully covered by policy.', walkthrough: ['Define escalation using authority, policy gaps, risk, and inability to progress.', 'Show an angry but routine case that should not escalate.', 'Show a calm exception request that must escalate.', 'Measure boundary accuracy on new cases.'], takeaway: 'Examples should teach the decision boundary, not stereotypes such as tone equals complexity.' },
    check: { question: 'When are few-shot examples most useful?', options: ['When the task already performs consistently', 'When prose rules leave an ambiguous decision boundary', 'As a replacement for every schema', 'To hide missing requirements'], answer: 1, explanation: 'Targeted examples clarify boundaries that remain ambiguous after explicit criteria.' },
    resources: [{ title: 'Prompting best practices', href: 'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices', note: 'Current instruction and example guidance.' }, promptOverview],
  }),
  'd4-3': detail({
    objectives: ['Choose JSON output versus strict tool use.', 'Separate structural validity from factual correctness.', 'Design parseable contracts for downstream systems.'],
    mentalModel: 'Structured output constrains the shape of an answer. It cannot prove that the values are supported, complete, authorized, or logically consistent.',
    how: { intro: 'Use schema-constrained JSON when the response itself is data. Use strict tool definitions when Claude must produce valid inputs to an operation. Tool choice separately determines whether a tool is optional or required.', bullets: ['Define types, required fields, enums, bounds, and nesting deliberately.', 'Represent legitimate absence without fabrication.', 'Include evidence where auditability matters.', 'Validate domain relationships after parsing.'] },
    decide: { intro: 'Choose the contract closest to the consumer. A pipeline ingesting an extraction wants JSON output; an application invoking a function wants a tool call. Both still need semantic and authorization checks.', bullets: ['Do not rely on “return JSON” prose for syntax guarantees.', 'Avoid schemas so rigid they force invented values.', 'Keep sensitive data out of property names and enum labels.', 'Version schemas when consumers depend on them.'] },
    scenario: { title: 'Worked example: invoice ingestion', situation: 'A parser must return supplier, invoice ID, currency, dates, totals, line items, and evidence.', walkthrough: ['Define nullable fields for absent source values.', 'Constrain currency and date formats.', 'Attach evidence references to extracted claims.', 'After schema validation, verify arithmetic and date relationships.'], takeaway: 'Use the schema to guarantee shape and a semantic validator to test whether the shaped data makes sense.' },
    check: { question: 'What does a valid structured-output schema guarantee?', options: ['Every value is true', 'The output conforms to the requested shape', 'The user authorized the action', 'Line-item totals are arithmetically correct'], answer: 1, explanation: 'Schema conformance guarantees structure, not truth, authorization, or cross-field semantics.' },
    resources: [structuredOutputs],
  }),
  'd4-4': detail({
    objectives: ['Represent missing and ambiguous data honestly.', 'Choose closed versus extensible categories.', 'Separate value, evidence, and confidence.'],
    mentalModel: 'A schema should make uncertainty representable. If the only valid shape demands certainty, the model is pressured to fabricate it.',
    how: { intro: 'Use optional or nullable fields for legitimate absence, explicit status fields for ambiguity, and evidence fields for provenance. Use enums for genuinely closed sets and an other-plus-detail pattern when novel values are legitimate.', bullets: ['Distinguish missing from not applicable.', 'Allow conflicting evidence to be represented.', 'Use confidence only with calibration and evidence.', 'Avoid a generic string when downstream decisions require a taxonomy.'] },
    decide: { intro: 'Design from real source variability and downstream behavior. For every field, decide what the consumer should do when the source omits it, contradicts itself, or uses an unknown category.', bullets: ['Do not make every field required by habit.', 'Do not use “other” to avoid defining known categories.', 'Keep raw evidence accessible for review.', 'Test sparse and contradictory documents.'] },
    scenario: { title: 'Worked example: conflicting invoice dates', situation: 'The header says 4 May while a footer says 5 May, and neither is clearly authoritative.', walkthrough: ['Set the normalized date to null or an explicit ambiguous state.', 'Capture both candidate values and locations.', 'Avoid choosing a value based only on position.', 'Route the record according to review policy.'], takeaway: 'Represent uncertainty as data so the system can respond safely instead of hiding it in a fabricated value.' },
    check: { question: 'What is safest when a source legitimately omits a field?', options: ['Require the model to infer it', 'Use nullable or optional representation', 'Insert an empty string without meaning', 'Retry until a value appears'], answer: 1, explanation: 'The schema should permit honest absence rather than force invention.' },
    resources: [structuredOutputs],
  }),
  'd4-5': detail({
    objectives: ['Add semantic checks after schema validation.', 'Retry only failures that new guidance can correct.', 'Route missing evidence to retrieval or review.'],
    mentalModel: 'Parsing asks “is this shaped correctly?” Semantic validation asks “can these values all be true together?”',
    how: { intro: 'After parsing, apply domain rules such as totals, chronological order, allowed state transitions, uniqueness, and cross-field consistency. Classify failures before choosing retry.', bullets: ['Retry correctable interpretation or formatting errors with specific feedback.', 'Include original source and failed output on repair attempts.', 'Do not retry evidence that is absent from the source.', 'Cap retries and measure how often they repair the result.'] },
    decide: { intro: 'A retry needs a plausible correction mechanism. If the problem is missing retrieval, policy ambiguity, or source contradiction, route to the component that can actually resolve it.', bullets: ['Separate validation errors by field and rule.', 'Preserve the first output for diagnosis.', 'Use deterministic arithmetic when possible.', 'Escalate high-impact unresolved contradictions.'] },
    scenario: { title: 'Worked example: invoice total mismatch', situation: 'The JSON is valid, but line items sum to 980 while the stated total is 1,080.', walkthrough: ['Flag the arithmetic invariant.', 'Check whether tax or shipping fields explain the difference.', 'Retry with the exact failed values and rule if source evidence can correct extraction.', 'Otherwise mark the record inconsistent for review.'], takeaway: 'Retries repair interpretable mistakes; they cannot manufacture missing evidence or resolve every contradiction.' },
    check: { question: 'When should the system avoid another model retry?', options: ['When JSON has a missing comma', 'When the source document does not contain the required value', 'When one enum label is misspelled', 'When a date was extracted from the wrong visible field'], answer: 1, explanation: 'No prompt can recover evidence that is absent. Return missing or route to retrieval/review.' },
    resources: [structuredOutputs, promptOverview],
  }),
  'd4-6': detail({
    objectives: ['Choose batch processing based on latency tolerance.', 'Correlate and selectively resubmit items.', 'Split large reviews into independent focused passes.'],
    mentalModel: 'Batching changes the operational envelope, not the reasoning contract. Multi-pass review changes focus by giving each pass a narrow question.',
    how: { intro: 'Use asynchronous batch processing for high-volume work that does not block a user or deployment. Assign stable custom IDs, store input/version metadata, and handle each result independently.', bullets: ['Do not batch latency-sensitive gates.', 'Resubmit failed items rather than the entire batch.', 'Separate local file review from cross-file integration review.', 'Require evidence and deduplicate findings across passes.'] },
    decide: { intro: 'Choose batch when throughput and cost matter more than immediate response. Choose focused passes when one broad review prompt loses precision across many categories or files.', bullets: ['Define completion and partial-failure policy.', 'Track per-item status and provenance.', 'Keep review contexts independent where useful.', 'Measure precision and coverage by pass.'] },
    scenario: { title: 'Worked example: overnight document analysis', situation: 'A company must process 50,000 documents by morning, and a small fraction may fail.', walkthrough: ['Submit items with stable custom IDs.', 'Store prompt and schema versions.', 'Collect results asynchronously.', 'Resubmit only transient or repairable failures and report final coverage.'], takeaway: 'Batch is appropriate because latency is tolerant and per-item correlation makes partial recovery possible.' },
    check: { question: 'Which workload is a poor fit for batch processing?', options: ['Overnight analysis of 50,000 documents', 'A blocking pre-merge approval gate', 'Monthly archive classification', 'Large offline evaluation run'], answer: 1, explanation: 'A blocking gate requires predictable immediate completion; batch is asynchronous.' },
    resources: [{ title: 'Message Batches', href: 'https://platform.claude.com/docs/en/build-with-claude/batch-processing', note: 'Asynchronous request submission and result handling.' }],
  }),

  'd5-1': detail({
    objectives: ['Treat context as a limited working set.', 'Separate durable facts from verbose evidence.', 'Trim tool results without losing decision-critical fields.'],
    mentalModel: 'The goal is not maximum context; it is maximum decision-relevant signal. Every extra token competes for attention and capacity.',
    how: { intro: 'Structure context into stable instructions, durable state, task-relevant evidence, recent interaction, and external storage. Normalize verbose tool results at the boundary.', bullets: ['Preserve exact IDs, amounts, dates, constraints, and commitments.', 'Select evidence relevant to the current decision.', 'Keep large raw artifacts outside the active prompt when possible.', 'Use retrieval to reacquire detail on demand.'] },
    decide: { intro: 'For each context item, ask what future decision needs it, how exact it must remain, and how cheaply it can be retrieved again.', bullets: ['Keep irreversible commitments verbatim or structured.', 'Summarize repetitive narrative.', 'Drop stale observations after state changes.', 'Measure token growth in long-running workflows.'] },
    scenario: { title: 'Worked example: return eligibility', situation: 'An order API returns 40 fields, but the decision needs customer ID, item, delivery date, return window, condition, and policy version.', walkthrough: ['Extract the six decision-critical fields.', 'Keep the source record ID and retrieval time.', 'Omit unrelated marketing and fulfillment metadata.', 'Re-fetch the source if a later decision needs another field.'], takeaway: 'Curate a compact working record while keeping enough provenance to verify or reacquire detail.' },
    check: { question: 'What is the best default context strategy?', options: ['Include every available field', 'Keep the smallest complete set needed for the current and foreseeable decisions', 'Remove all prior messages', 'Rely only on model memory'], answer: 1, explanation: 'Relevant, structured context reduces distraction while preserving what the task actually needs.' },
    resources: [contextWindows, { title: 'Manage tool context', href: 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/manage-tool-context', note: 'Strategies for tool-definition and result growth.' }],
  }),
  'd5-2': detail({
    objectives: ['Preserve critical facts through compaction.', 'Use isolated workers for verbose discovery.', 'Distinguish prompt caching from context reduction.'],
    mentalModel: 'Compaction is lossy compression. Decide in advance which facts must remain exact and keep them in a durable structured layer.',
    how: { intro: 'Long sessions accumulate messages, tools, results, and artifacts. Preserve exact identifiers, values, decisions, source mappings, and pending commitments outside narrative summaries. Isolate noisy exploration where possible.', bullets: ['Record a compact case-facts or task-state block.', 'Keep source references with claims.', 'Use subagents for large discovery traces.', 'Treat prompt caching as cost optimization, not free context capacity.'] },
    decide: { intro: 'Compact material that is redundant or recoverable. Preserve anything whose distortion could cause a wrong action, broken handoff, or unverifiable claim.', bullets: ['Mark unresolved ambiguity explicitly.', 'Retain the latest authoritative state.', 'Reacquire stale evidence after long pauses.', 'Test recovery from the saved state alone.'] },
    scenario: { title: 'Worked example: multi-turn support case', situation: 'A case spans dozens of messages and includes two promised dates, a refund amount, and a policy exception.', walkthrough: ['Store exact dates, amount, approver, and policy version in structured state.', 'Summarize conversational repetition.', 'Keep links to the supporting messages.', 'Verify the state block before compaction or handoff.'], takeaway: 'Critical commitments belong in durable structured state, not only in a lossy conversation summary.' },
    check: { question: 'What does prompt caching change?', options: ['It removes cached tokens from the context window', 'It can reduce repeated-input cost while the tokens still occupy context', 'It guarantees perfect recall', 'It replaces compaction'], answer: 1, explanation: 'Caching affects cost and latency; cached input still contributes to the context window.' },
    resources: [contextWindows, claudeCodeOverview],
  }),
  'd5-3': detail({
    objectives: ['Define escalation from policy and authority.', 'Ask discriminating clarification questions.', 'Avoid sentiment and raw confidence as sole triggers.'],
    mentalModel: 'Escalation is routing based on authority, risk, evidence, and progress—not a reaction to tone.',
    how: { intro: 'Escalate when a user asks for a human, policy is missing or exceptional, authority is insufficient, high-impact ambiguity remains, or safe recovery cannot make progress. Ask for a fact that separates possible records when ambiguity is resolvable.', bullets: ['Honor explicit human requests.', 'Escalate policy exceptions and authority limits.', 'Ask for a discriminating identifier rather than guessing.', 'Record verified context so the human can continue.'] },
    decide: { intro: 'Tie escalation to observable conditions and consequence. Confidence may inform routing only after calibration against labeled outcomes.', bullets: ['Do not escalate solely because the user sounds angry.', 'Do not guess among matching accounts.', 'Avoid repeated retries after the same permanent barrier.', 'State what decision or evidence is missing.'] },
    scenario: { title: 'Worked example: two matching accounts', situation: 'A customer name and email fragment match two accounts with different active subscriptions.', walkthrough: ['Do not select the first match.', 'Ask for a safe discriminating identifier.', 'Verify it against the candidate records.', 'Escalate if policy does not permit resolution from available identifiers.'], takeaway: 'Resolve ambiguity with the smallest safe clarifying fact; escalate when the system lacks authority or a valid resolution path.' },
    check: { question: 'Which signal alone is insufficient for escalation?', options: ['The user explicitly asks for a human', 'The request requires a policy exception', 'The user expresses anger', 'The action exceeds the agent’s authority'], answer: 2, explanation: 'Sentiment does not establish complexity or authority. Use policy, evidence, risk, and explicit requests.' },
    resources: [effectiveAgents],
  }),
  'd5-4': detail({
    objectives: ['Distinguish access failure from valid empty evidence.', 'Preserve partial results and failed coverage.', 'Choose local recovery versus coordinator escalation.'],
    mentalModel: 'An upstream error is part of the evidence state. Hiding it as “nothing found” converts uncertainty into false certainty.',
    how: { intro: 'Specialists should classify failures, attempt safe local recovery, and return partial findings plus structured error details. The coordinator decides whether to retry, switch sources, continue with a labeled gap, or escalate.', bullets: ['Keep valid empty results distinct from retrieval failure.', 'Return attempts, error class, retryability, and affected coverage.', 'Preserve successful branches.', 'Annotate downstream conclusions limited by missing evidence.'] },
    decide: { intro: 'Recover locally when the specialist has the context and authority to do so. Escalate to the coordinator when the failure changes overall coverage, budget, or strategy.', bullets: ['Retry transient errors within a bounded budget.', 'Do not retry permission failures blindly.', 'Use approved alternatives when equivalent.', 'Never omit a failed source from the final synthesis.'] },
    scenario: { title: 'Worked example: research source timeout', situation: 'Three sources are required; two succeed and the third repeatedly times out.', walkthrough: ['Retry the failed source within policy.', 'Keep the two successful evidence sets.', 'Return the failed source, attempts, and coverage impact.', 'Let the coordinator choose an alternative or publish with an explicit gap.'], takeaway: 'Partial success remains useful only when missing coverage is visible and cannot be mistaken for negative evidence.' },
    check: { question: 'Why is turning a timeout into an empty result dangerous?', options: ['It makes the response shorter', 'It makes missing evidence look like evidence that nothing exists', 'It prevents parallelism', 'It always causes a schema error'], answer: 1, explanation: 'Failure and zero matches imply different facts and lead to different recovery decisions.' },
    resources: [{ title: 'Handle tool calls', href: 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/handle-tool-calls', note: 'Tool errors and result signaling.' }],
  }),
  'd5-5': detail({
    objectives: ['Calibrate review thresholds using labeled data.', 'Measure performance by meaningful segment.', 'Sample high-confidence output to detect drift.'],
    mentalModel: 'A confidence score becomes operational only after calibration shows what that score means for this task, segment, and consequence.',
    how: { intro: 'Compare model outputs and confidence signals with labeled outcomes. Measure by document type, field, language, source quality, and other segments that can hide minority failure modes.', bullets: ['Set thresholds from observed risk, not intuition.', 'Route contradictory and high-impact cases to review.', 'Sample some high-confidence outputs.', 'Monitor drift after model, prompt, schema, or data changes.'] },
    decide: { intro: 'Review policy should minimize expected harm under a cost budget. A low-risk field may tolerate lower certainty than a payment amount or legal classification.', bullets: ['Use field- and segment-specific thresholds.', 'Track false accepts and false rejects.', 'Recalibrate after material changes.', 'Do not rely on one aggregate accuracy number.'] },
    scenario: { title: 'Worked example: document extraction', situation: 'Overall accuracy is 97%, but handwritten quantities in one supplier format are only 71% accurate.', walkthrough: ['Identify the failing segment.', 'Route that segment to review or a specialized path.', 'Continue sampling high-confidence outputs elsewhere.', 'Measure whether the targeted control improves risk and cost.'], takeaway: 'Segment-level performance, not the attractive aggregate, should drive review policy.' },
    check: { question: 'What is wrong with reducing review because aggregate accuracy is 97%?', options: ['Nothing; 97% is always sufficient', 'The average may hide a dangerous low-performing segment', 'Human review cannot improve accuracy', 'Confidence is always binary'], answer: 1, explanation: 'Aggregate performance can conceal systematic failure in a consequential minority segment.' },
    resources: [{ title: 'Evaluate models', href: 'https://platform.claude.com/docs/en/test-and-evaluate/overview', note: 'Building and running representative evaluations.' }],
  }),
  'd5-6': detail({
    objectives: ['Keep claim-to-source mappings through synthesis.', 'Represent credible conflict without false resolution.', 'Use dates and methodology to interpret differences.'],
    mentalModel: 'A synthesized claim is only as auditable as the evidence link that survives with it. Compression must not detach conclusions from provenance.',
    how: { intro: 'Carry source ID, URL or location, excerpt, date, method, and uncertainty with each claim. When credible sources disagree, preserve both and explain relevant temporal or methodological differences.', bullets: ['Do not average incompatible values.', 'Prefer source-specific claims over vague consensus language.', 'Distinguish established, contested, and missing findings.', 'Keep failed-source coverage visible.'] },
    decide: { intro: 'Resolve a conflict only when there is a defensible rule such as newer authoritative data or a scope difference. Otherwise report the disagreement and what evidence would settle it.', bullets: ['Compare publication and measurement dates.', 'Check definitions and populations.', 'Separate primary from secondary reporting.', 'Retain exact numbers and units.'] },
    scenario: { title: 'Worked example: conflicting revenue figures', situation: 'An annual report gives $420M for fiscal year revenue while a later article gives $390M without specifying period.', walkthrough: ['Record each value with source, date, and stated period.', 'Do not average them.', 'Treat the annual report as authoritative for its defined fiscal period.', 'Label the article figure as ambiguous until its scope is established.'], takeaway: 'Preserve both claims and their contexts; disagreement is information, not noise to remove.' },
    check: { question: 'What is the safest response to two credible but incompatible figures?', options: ['Average them', 'Pick the larger value', 'Preserve both with source, date, and methodological context', 'Omit all citations'], answer: 2, explanation: 'Provenance and context allow readers to understand or later resolve the disagreement without invented certainty.' },
    resources: [contextWindows, { title: 'Citations', href: 'https://platform.claude.com/docs/en/build-with-claude/citations', note: 'Grounding generated claims in source material.' }],
  }),
};

for (const [id, supplement] of Object.entries(lessonSupplements)) {
  const base = lessonDetails[id];
  if (!base) continue;

  lessonDetails[id] = {
    ...base,
    steps: supplement.steps,
    sections: [base.sections[0], ...supplement.sections, ...base.sections.slice(1)],
    checks: [...base.checks, ...supplement.checks],
  };
}
